import type { Metadata } from "next";
import { CartProvider } from "../context/cartContext";
import "./styles/App.scss";
import { Header } from "@/components/layout/header/header";
import { Footer } from "@/components/layout/footer/footer";
import Contacts from "./contacts/contacts";
import stl from "../app/styles/_page.module.scss";

export const metadata: Metadata = {
  title: "Toy house",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Header/>
          {children}
          <Contacts/>
          <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
